import type { UltraModule } from './base-module';

/** Loader: returns the module instance when needed. Modules are lazy-loaded as separate chunks. */
export type ModuleLoader = () => Promise<UltraModule>;

/** Core module loaders. Implementations are lazy-loaded on demand to reduce initial bundle size. */
export const coreLoaders: Record<string, ModuleLoader> = {
  text: () => import(/* webpackChunkName: "text" */ './text-module').then(m => new m.UltraTextModule()),
  separator: () => import(/* webpackChunkName: "separator" */ './separator-module').then(m => new m.UltraSeparatorModule()),
  image: () => import(/* webpackChunkName: "image" */ './image-module').then(m => new m.UltraImageModule()),
  info: () => import(/* webpackChunkName: "info" */ './info-module').then(m => new m.UltraInfoModule()),
  bar: () => import(/* webpackChunkName: "bar" */ './bar-module').then(m => new m.UltraBarModule()),
  gauge: () => import(/* webpackChunkName: "gauge" */ './gauge-module').then(m => new m.UltraGaugeModule()),
  icon: () => import(/* webpackChunkName: "icon" */ './icon-module').then(m => new m.UltraIconModule()),
  button: () => import(/* webpackChunkName: "button" */ './button-module').then(m => new m.UltraButtonModule()),
  spinbox: () => import(/* webpackChunkName: "spinbox" */ './spinbox-module').then(m => new m.UltraSpinboxModule()),
  markdown: () => import(/* webpackChunkName: "markdown" */ './markdown-module').then(m => new m.UltraMarkdownModule()),
  horizontal: () => import(/* webpackChunkName: "horizontal" */ './horizontal-module').then(m => new m.UltraHorizontalModule()),
  vertical: () => import(/* webpackChunkName: "vertical" */ './vertical-module').then(m => new m.UltraVerticalModule()),
  accordion: () => import(/* webpackChunkName: "accordion" */ './accordion-module').then(m => new m.UltraAccordionModule()),
  popup: () => import(/* webpackChunkName: "popup" */ './popup-module').then(m => new m.UltraPopupModule()),
  slider: () => import(/* webpackChunkName: "slider" */ './slider-module').then(m => new m.UltraSliderModule()),
  slider_control: () => import(/* webpackChunkName: "slider-control" */ './slider-control-module').then(m => new m.UltraSliderControlModule()),
  pagebreak: () => import(/* webpackChunkName: "pagebreak" */ './pagebreak-module').then(m => new m.UltraPageBreakModule()),
  camera: () => import(/* webpackChunkName: "camera" */ './camera-module').then(m => new m.UltraCameraModule()),
  graphs: () => import(/* webpackChunkName: "graphs" */ './graphs-module').then(m => new m.UltraGraphsModule()),
  dropdown: () => import(/* webpackChunkName: "dropdown" */ './dropdown-module').then(m => new m.UltraDropdownModule()),
  light: () => import(/* webpackChunkName: "light" */ './light-module').then(m => new m.UltraLightModule()),
  map: () => import(/* webpackChunkName: "map" */ './map-module').then(m => new m.UltraMapModule()),
  animated_clock: () => import(/* webpackChunkName: "animated-clock" */ './animated-clock-module').then(m => new m.UltraAnimatedClockModule()),
  animated_weather: () => import(/* webpackChunkName: "animated-weather" */ './animated-weather-module').then(m => new m.UltraAnimatedWeatherModule()),
  animated_forecast: () => import(/* webpackChunkName: "animated-forecast" */ './animated-forecast-module').then(m => new m.UltraAnimatedForecastModule()),
  external_card: () => import(/* webpackChunkName: "external-card" */ './external-card-module').then(m => new m.UltraExternalCardModule()),
  native_card: () => import(/* webpackChunkName: "native-card" */ './native-card-module').then(m => new m.UltraNativeCardModule()),
  video_bg: () => import(/* webpackChunkName: "video-bg" */ './video-bg-module').then(m => new m.UltraVideoBgModule()),
  climate: () => import(/* webpackChunkName: "climate" */ './climate-module').then(m => new m.UltraClimateModule()),
  dynamic_weather: () => import(/* webpackChunkName: "dynamic-weather" */ './dynamic-weather-module').then(m => new m.UltraDynamicWeatherModule()),
  background: () => import(/* webpackChunkName: "background" */ './background-module').then(m => new m.UltraBackgroundModule()),
  status_summary: () => import(/* webpackChunkName: "status-summary" */ './status-summary-module').then(m => new m.UltraStatusSummaryModule()),
  toggle: () => import(/* webpackChunkName: "toggle" */ './toggle-module').then(m => new m.UltraToggleModule()),
  tabs: () => import(/* webpackChunkName: "tabs" */ './tabs-module').then(m => new m.UltraTabsModule()),
  calendar: () => import(/* webpackChunkName: "calendar" */ './calendar-module').then(m => new m.UltraCalendarModule()),
  sports_score: () => import(/* webpackChunkName: "sports-score" */ './sports-score-module').then(m => new m.UltraSportsScoreModule()),
  badge_of_honor: () => import(/* webpackChunkName: "badge-of-honor" */ './badge-of-honor-module').then(m => new m.UltraBadgeOfHonorModule()),
  grid: () => import(/* webpackChunkName: "grid" */ './grid-module').then(m => new m.UltraGridModule()),
  vacuum: () => import(/* webpackChunkName: "vacuum" */ './vacuum-module').then(m => new m.UltraVacuumModule()),
  media_player: () => import(/* webpackChunkName: "media-player" */ './media-player-module').then(m => new m.UltraMediaPlayerModule()),
  people: () => import(/* webpackChunkName: "people" */ './people-module').then(m => new m.UltraPeopleModule()),
  navigation: () => import(/* webpackChunkName: "navigation" */ './navigation-module').then(m => new m.UltraNavigationModule()),
  timer: () => import(/* webpackChunkName: "timer" */ './timer-module').then(m => new m.UltraTimerModule()),
  cover: () => import(/* webpackChunkName: "cover" */ './cover-module').then(m => new m.UltraCoverModule()),
  fan: () => import(/* webpackChunkName: "fan" */ './fan-module').then(m => new m.UltraFanModule()),
  lock: () => import(/* webpackChunkName: "lock" */ './lock-module').then(m => new m.UltraLockModule()),
  'dynamic-list': () => import(/* webpackChunkName: "dynamic-list" */ './dynamic-list-module').then(m => new m.UltraDynamicListModule()),
  qr_code: () => import(/* webpackChunkName: "qr-code" */ './qr-code-module').then(m => new m.UltraQrCodeModule()),
  energy_display: () => import(/* webpackChunkName: "energy-display" */ './energy-display-module').then(m => new m.UltraEnergyDisplayModule()),
  living_canvas: () => import(/* webpackChunkName: "living-canvas" */ './living-canvas-module').then(m => new m.UltraLivingCanvasModule()),
  text_input: () => import(/* webpackChunkName: "text-input" */ './text-input-module').then(m => new m.UltraTextInputModule()),
  datetime_input: () => import(/* webpackChunkName: "datetime-input" */ './datetime-input-module').then(m => new m.UltraDatetimeInputModule()),
  number_input: () => import(/* webpackChunkName: "number-input" */ './number-input-module').then(m => new m.UltraNumberInputModule()),
  slider_input: () => import(/* webpackChunkName: "slider-input" */ './slider-input-module').then(m => new m.UltraSliderInputModule()),
  select_input: () => import(/* webpackChunkName: "select-input" */ './select-input-module').then(m => new m.UltraSelectInputModule()),
  boolean_input: () => import(/* webpackChunkName: "boolean-input" */ './boolean-input-module').then(m => new m.UltraBooleanInputModule()),
  button_input: () => import(/* webpackChunkName: "button-input" */ './button-input-module').then(m => new m.UltraButtonInputModule()),
  counter_input: () => import(/* webpackChunkName: "counter-input" */ './counter-input-module').then(m => new m.UltraCounterInputModule()),
  color_input: () => import(/* webpackChunkName: "color-input" */ './color-input-module').then(m => new m.UltraColorInputModule()),
  activity_feed: () => import(/* webpackChunkName: "activity-feed" */ './activity-feed-module').then(m => new m.UltraActivityFeedModule()),
  virtual_pet: () => import(/* webpackChunkName: "virtual-pet" */ './virtual-pet-module').then(m => new m.UltraVirtualPetModule()),
};
