import type { UltraModule } from './base-module';

/** Loader: returns the module instance when needed. Uses eager mode so everything is bundled into ultra-card.js for HACS compatibility. */
export type ModuleLoader = () => Promise<UltraModule>;

/** Core module loaders. Eager-bundled into the main file while keeping the async API surface. */
export const coreLoaders: Record<string, ModuleLoader> = {
  text: () => import(/* webpackMode: "eager" */ './text-module').then(m => new m.UltraTextModule()),
  separator: () => import(/* webpackMode: "eager" */ './separator-module').then(m => new m.UltraSeparatorModule()),
  image: () => import(/* webpackMode: "eager" */ './image-module').then(m => new m.UltraImageModule()),
  info: () => import(/* webpackMode: "eager" */ './info-module').then(m => new m.UltraInfoModule()),
  bar: () => import(/* webpackMode: "eager" */ './bar-module').then(m => new m.UltraBarModule()),
  gauge: () => import(/* webpackMode: "eager" */ './gauge-module').then(m => new m.UltraGaugeModule()),
  icon: () => import(/* webpackMode: "eager" */ './icon-module').then(m => new m.UltraIconModule()),
  button: () => import(/* webpackMode: "eager" */ './button-module').then(m => new m.UltraButtonModule()),
  spinbox: () => import(/* webpackMode: "eager" */ './spinbox-module').then(m => new m.UltraSpinboxModule()),
  markdown: () => import(/* webpackMode: "eager" */ './markdown-module').then(m => new m.UltraMarkdownModule()),
  horizontal: () => import(/* webpackMode: "eager" */ './horizontal-module').then(m => new m.UltraHorizontalModule()),
  vertical: () => import(/* webpackMode: "eager" */ './vertical-module').then(m => new m.UltraVerticalModule()),
  accordion: () => import(/* webpackMode: "eager" */ './accordion-module').then(m => new m.UltraAccordionModule()),
  popup: () => import(/* webpackMode: "eager" */ './popup-module').then(m => new m.UltraPopupModule()),
  slider: () => import(/* webpackMode: "eager" */ './slider-module').then(m => new m.UltraSliderModule()),
  slider_control: () => import(/* webpackMode: "eager" */ './slider-control-module').then(m => new m.UltraSliderControlModule()),
  pagebreak: () => import(/* webpackMode: "eager" */ './pagebreak-module').then(m => new m.UltraPageBreakModule()),
  camera: () => import(/* webpackMode: "eager" */ './camera-module').then(m => new m.UltraCameraModule()),
  graphs: () => import(/* webpackMode: "eager" */ './graphs-module').then(m => new m.UltraGraphsModule()),
  dropdown: () => import(/* webpackMode: "eager" */ './dropdown-module').then(m => new m.UltraDropdownModule()),
  light: () => import(/* webpackMode: "eager" */ './light-module').then(m => new m.UltraLightModule()),
  map: () => import(/* webpackMode: "eager" */ './map-module').then(m => new m.UltraMapModule()),
  animated_clock: () => import(/* webpackMode: "eager" */ './animated-clock-module').then(m => new m.UltraAnimatedClockModule()),
  animated_weather: () => import(/* webpackMode: "eager" */ './animated-weather-module').then(m => new m.UltraAnimatedWeatherModule()),
  animated_forecast: () => import(/* webpackMode: "eager" */ './animated-forecast-module').then(m => new m.UltraAnimatedForecastModule()),
  external_card: () => import(/* webpackMode: "eager" */ './external-card-module').then(m => new m.UltraExternalCardModule()),
  native_card: () => import(/* webpackMode: "eager" */ './native-card-module').then(m => new m.UltraNativeCardModule()),
  video_bg: () => import(/* webpackMode: "eager" */ './video-bg-module').then(m => new m.UltraVideoBgModule()),
  climate: () => import(/* webpackMode: "eager" */ './climate-module').then(m => new m.UltraClimateModule()),
  dynamic_weather: () => import(/* webpackMode: "eager" */ './dynamic-weather-module').then(m => new m.UltraDynamicWeatherModule()),
  background: () => import(/* webpackMode: "eager" */ './background-module').then(m => new m.UltraBackgroundModule()),
  status_summary: () => import(/* webpackMode: "eager" */ './status-summary-module').then(m => new m.UltraStatusSummaryModule()),
  toggle: () => import(/* webpackMode: "eager" */ './toggle-module').then(m => new m.UltraToggleModule()),
  tabs: () => import(/* webpackMode: "eager" */ './tabs-module').then(m => new m.UltraTabsModule()),
  calendar: () => import(/* webpackMode: "eager" */ './calendar-module').then(m => new m.UltraCalendarModule()),
  sports_score: () => import(/* webpackMode: "eager" */ './sports-score-module').then(m => new m.UltraSportsScoreModule()),
  badge_of_honor: () => import(/* webpackMode: "eager" */ './badge-of-honor-module').then(m => new m.UltraBadgeOfHonorModule()),
  grid: () => import(/* webpackMode: "eager" */ './grid-module').then(m => new m.UltraGridModule()),
  vacuum: () => import(/* webpackMode: "eager" */ './vacuum-module').then(m => new m.UltraVacuumModule()),
  media_player: () => import(/* webpackMode: "eager" */ './media-player-module').then(m => new m.UltraMediaPlayerModule()),
  people: () => import(/* webpackMode: "eager" */ './people-module').then(m => new m.UltraPeopleModule()),
  navigation: () => import(/* webpackMode: "eager" */ './navigation-module').then(m => new m.UltraNavigationModule()),
  timer: () => import(/* webpackMode: "eager" */ './timer-module').then(m => new m.UltraTimerModule()),
  cover: () => import(/* webpackMode: "eager" */ './cover-module').then(m => new m.UltraCoverModule()),
  fan: () => import(/* webpackMode: "eager" */ './fan-module').then(m => new m.UltraFanModule()),
  lock: () => import(/* webpackMode: "eager" */ './lock-module').then(m => new m.UltraLockModule()),
  'dynamic-list': () => import(/* webpackMode: "eager" */ './dynamic-list-module').then(m => new m.UltraDynamicListModule()),
  qr_code: () => import(/* webpackMode: "eager" */ './qr-code-module').then(m => new m.UltraQrCodeModule()),
  energy_display: () => import(/* webpackMode: "eager" */ './energy-display-module').then(m => new m.UltraEnergyDisplayModule()),
  living_canvas: () => import(/* webpackMode: "eager" */ './living-canvas-module').then(m => new m.UltraLivingCanvasModule()),
  text_input: () => import(/* webpackMode: "eager" */ './text-input-module').then(m => new m.UltraTextInputModule()),
  datetime_input: () => import(/* webpackMode: "eager" */ './datetime-input-module').then(m => new m.UltraDatetimeInputModule()),
  number_input: () => import(/* webpackMode: "eager" */ './number-input-module').then(m => new m.UltraNumberInputModule()),
  slider_input: () => import(/* webpackMode: "eager" */ './slider-input-module').then(m => new m.UltraSliderInputModule()),
  select_input: () => import(/* webpackMode: "eager" */ './select-input-module').then(m => new m.UltraSelectInputModule()),
  boolean_input: () => import(/* webpackMode: "eager" */ './boolean-input-module').then(m => new m.UltraBooleanInputModule()),
  button_input: () => import(/* webpackMode: "eager" */ './button-input-module').then(m => new m.UltraButtonInputModule()),
  counter_input: () => import(/* webpackMode: "eager" */ './counter-input-module').then(m => new m.UltraCounterInputModule()),
  color_input: () => import(/* webpackMode: "eager" */ './color-input-module').then(m => new m.UltraColorInputModule()),
  activity_feed: () => import(/* webpackMode: "eager" */ './activity-feed-module').then(m => new m.UltraActivityFeedModule()),
  area_summary: () => import(/* webpackMode: "eager" */ './area-summary-module').then(m => new m.UltraAreaSummaryModule()),
  virtual_pet: () => import(/* webpackMode: "eager" */ './virtual-pet-module').then(m => new m.UltraVirtualPetModule()),
};
