import type { UltraModule } from './base-module';

/** Loader: returns the module instance when needed. Dynamic import keeps implementation in separate chunks. */
export type ModuleLoader = () => Promise<UltraModule>;

/** Lazy loaders for core modules. Only the loaded module chunk is fetched when ensureModuleLoaded(type) is called. */
export const coreLoaders: Record<string, ModuleLoader> = {
  text: () => import('./text-module').then(m => new m.UltraTextModule()),
  separator: () => import('./separator-module').then(m => new m.UltraSeparatorModule()),
  image: () => import('./image-module').then(m => new m.UltraImageModule()),
  info: () => import('./info-module').then(m => new m.UltraInfoModule()),
  bar: () => import('./bar-module').then(m => new m.UltraBarModule()),
  gauge: () => import('./gauge-module').then(m => new m.UltraGaugeModule()),
  icon: () => import('./icon-module').then(m => new m.UltraIconModule()),
  button: () => import('./button-module').then(m => new m.UltraButtonModule()),
  spinbox: () => import('./spinbox-module').then(m => new m.UltraSpinboxModule()),
  markdown: () => import('./markdown-module').then(m => new m.UltraMarkdownModule()),
  horizontal: () => import('./horizontal-module').then(m => new m.UltraHorizontalModule()),
  vertical: () => import('./vertical-module').then(m => new m.UltraVerticalModule()),
  accordion: () => import('./accordion-module').then(m => new m.UltraAccordionModule()),
  popup: () => import('./popup-module').then(m => new m.UltraPopupModule()),
  slider: () => import('./slider-module').then(m => new m.UltraSliderModule()),
  slider_control: () => import('./slider-control-module').then(m => new m.UltraSliderControlModule()),
  pagebreak: () => import('./pagebreak-module').then(m => new m.UltraPageBreakModule()),
  camera: () => import('./camera-module').then(m => new m.UltraCameraModule()),
  graphs: () => import('./graphs-module').then(m => new m.UltraGraphsModule()),
  dropdown: () => import('./dropdown-module').then(m => new m.UltraDropdownModule()),
  light: () => import('./light-module').then(m => new m.UltraLightModule()),
  map: () => import('./map-module').then(m => new m.UltraMapModule()),
  animated_clock: () => import('./animated-clock-module').then(m => new m.UltraAnimatedClockModule()),
  animated_weather: () => import('./animated-weather-module').then(m => new m.UltraAnimatedWeatherModule()),
  animated_forecast: () => import('./animated-forecast-module').then(m => new m.UltraAnimatedForecastModule()),
  external_card: () => import('./external-card-module').then(m => new m.UltraExternalCardModule()),
  native_card: () => import('./native-card-module').then(m => new m.UltraNativeCardModule()),
  video_bg: () => import('./video-bg-module').then(m => new m.UltraVideoBgModule()),
  climate: () => import('./climate-module').then(m => new m.UltraClimateModule()),
  dynamic_weather: () => import('./dynamic-weather-module').then(m => new m.UltraDynamicWeatherModule()),
  background: () => import('./background-module').then(m => new m.UltraBackgroundModule()),
  status_summary: () => import('./status-summary-module').then(m => new m.UltraStatusSummaryModule()),
  toggle: () => import('./toggle-module').then(m => new m.UltraToggleModule()),
  tabs: () => import('./tabs-module').then(m => new m.UltraTabsModule()),
  calendar: () => import('./calendar-module').then(m => new m.UltraCalendarModule()),
  sports_score: () => import('./sports-score-module').then(m => new m.UltraSportsScoreModule()),
  badge_of_honor: () => import('./badge-of-honor-module').then(m => new m.UltraBadgeOfHonorModule()),
  grid: () => import('./grid-module').then(m => new m.UltraGridModule()),
  vacuum: () => import('./vacuum-module').then(m => new m.UltraVacuumModule()),
  media_player: () => import('./media-player-module').then(m => new m.UltraMediaPlayerModule()),
  people: () => import('./people-module').then(m => new m.UltraPeopleModule()),
  navigation: () => import('./navigation-module').then(m => new m.UltraNavigationModule()),
  timer: () => import('./timer-module').then(m => new m.UltraTimerModule()),
  cover: () => import('./cover-module').then(m => new m.UltraCoverModule()),
  'dynamic-list': () => import('./dynamic-list-module').then(m => new m.UltraDynamicListModule()),
  qr_code: () => import('./qr-code-module').then(m => new m.UltraQrCodeModule()),
  energy_display: () => import('./energy-display-module').then(m => new m.UltraEnergyDisplayModule()),
};
