import { LitElement, TemplateResult } from 'lit';
import { HomeAssistant } from 'custom-card-helpers';
import { UltraCardConfig } from '../../types';
import '../../components/color-picker';
export declare class LayoutTab extends LitElement {
    hass: HomeAssistant;
    config: UltraCardConfig;
    private _showModuleSelector;
    private _selectedRowIndex;
    private _selectedColumnIndex;
    private _showModuleSettings;
    private _selectedModule;
    private _activeModuleTab;
    private _activeDesignSubtab;
    private _configChanged;
    private _updateConfig;
    private _updateLayout;
    private _addRow;
    private _deleteRow;
    private _openModuleSelector;
    private _addModule;
    private _openModuleSettings;
    private _updateModule;
    private _loadGoogleFont;
    private _renderModulePreview;
    private _renderSingleModule;
    private _renderModuleSettings;
    private _renderGeneralTab;
    private _renderLogicTab;
    private _renderDesignTab;
    private _renderTextDesignTab;
    private _renderBackgroundDesignTab;
    private _renderSpacingDesignTab;
    private _renderBorderDesignTab;
    protected render(): TemplateResult;
    private _renderModuleSelector;
    static get styles(): import("lit").CSSResult;
}
